CREATE TABLE library_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_library_user_role CHECK (role IN ('CLIENT', 'OWNER'))
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_book_total_copies CHECK (total_copies > 0),
    CONSTRAINT chk_book_available_copies
        CHECK (available_copies >= 0 AND available_copies <= total_copies)
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    borrower_id BIGINT NOT NULL,
    borrowed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    returned_at TIMESTAMP WITH TIME ZONE,
    returned_late BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_loan_book
        FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_loan_borrower
        FOREIGN KEY (borrower_id) REFERENCES library_users (id),
    CONSTRAINT chk_loan_due_after_borrow
        CHECK (due_at > borrowed_at),
    CONSTRAINT chk_active_loan_not_late
        CHECK (returned_at IS NOT NULL OR returned_late = FALSE)
);

CREATE INDEX idx_books_title ON books (title);
CREATE INDEX idx_books_author ON books (author);
CREATE INDEX idx_loans_borrower ON loans (borrower_id);
CREATE INDEX idx_loans_book ON loans (book_id);
CREATE INDEX idx_loans_returned_at ON loans (returned_at);

