CREATE TABLE late_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL UNIQUE,
    days_late INTEGER NOT NULL,
    daily_rate NUMERIC(10, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    settled_at TIMESTAMP WITH TIME ZONE,
    settlement_note VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_late_fee_loan
        FOREIGN KEY (loan_id) REFERENCES loans (id),
    CONSTRAINT chk_late_fee_days
        CHECK (days_late > 0),
    CONSTRAINT chk_late_fee_daily_rate
        CHECK (daily_rate > 0),
    CONSTRAINT chk_late_fee_amount
        CHECK (amount = daily_rate * days_late),
    CONSTRAINT chk_late_fee_currency
        CHECK (CHAR_LENGTH(currency) = 3 AND currency = UPPER(currency)),
    CONSTRAINT chk_late_fee_status
        CHECK (status IN ('OUTSTANDING', 'PAID', 'WAIVED')),
    CONSTRAINT chk_late_fee_settlement
        CHECK (
            (status = 'OUTSTANDING' AND settled_at IS NULL)
            OR (status IN ('PAID', 'WAIVED') AND settled_at IS NOT NULL)
        )
);

CREATE INDEX idx_late_fees_status ON late_fees (status);
CREATE INDEX idx_late_fees_registered_at ON late_fees (registered_at);
