CREATE TABLE book_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    borrower_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    active_key VARCHAR(50) UNIQUE,
    queued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ready_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    fulfilled_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    expired_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_reservation_book
        FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_reservation_borrower
        FOREIGN KEY (borrower_id) REFERENCES library_users (id),
    CONSTRAINT chk_reservation_status
        CHECK (status IN ('WAITING', 'READY', 'FULFILLED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_reservation_ready_window
        CHECK (
            (ready_at IS NULL AND expires_at IS NULL)
            OR (ready_at IS NOT NULL AND expires_at IS NOT NULL AND expires_at > ready_at)
        ),
    CONSTRAINT chk_reservation_lifecycle
        CHECK (
            (status = 'WAITING'
                AND active_key IS NOT NULL
                AND ready_at IS NULL
                AND fulfilled_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL)
            OR (status = 'READY'
                AND active_key IS NOT NULL
                AND ready_at IS NOT NULL
                AND fulfilled_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL)
            OR (status = 'FULFILLED'
                AND active_key IS NULL
                AND ready_at IS NOT NULL
                AND fulfilled_at IS NOT NULL
                AND cancelled_at IS NULL
                AND expired_at IS NULL)
            OR (status = 'CANCELLED'
                AND active_key IS NULL
                AND fulfilled_at IS NULL
                AND cancelled_at IS NOT NULL
                AND expired_at IS NULL)
            OR (status = 'EXPIRED'
                AND active_key IS NULL
                AND ready_at IS NOT NULL
                AND fulfilled_at IS NULL
                AND cancelled_at IS NULL
                AND expired_at IS NOT NULL)
        )
);

CREATE INDEX idx_reservations_queue
    ON book_reservations (book_id, status, queued_at, id);
CREATE INDEX idx_reservations_borrower
    ON book_reservations (borrower_id, queued_at);
CREATE INDEX idx_reservations_expiry
    ON book_reservations (status, expires_at);
